doc

diff --git a/.github/workflows/presubmit.yml b/.github/workflows/presubmit.yml
--- a/.github/workflows/presubmit.yml
+++ b/.github/workflows/presubmit.yml
@@ -22,7 +22,7 @@ jobs:
           git diff --name-only @^
 
           chore_files=( LICENSE CONTRIBUTING.md README.md netlify.toml )
-          chore_dirs=( docs )
+          chore_dirs=( docs .github )
           run_job=false
 
           for file in $(git diff --name-only @^); do
@@ -89,46 +89,46 @@ jobs:
           git diff _fake_squash _enforced_format --exit-code
 
   check_static_analyzer:
-    name: Check Static Analyzer
-    runs-on: ubuntu-latest
-    needs: check_files
-    if: needs.check_files.outputs.run_job == 'true'
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: "recursive"
+      name: Check Static Analyzer
+      runs-on: ubuntu-latest
+      needs: check_files
+      if: needs.check_files.outputs.run_job == 'true'
+      steps:
+        - uses: actions/checkout@v2
+          with:
+            submodules: "recursive"
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.8
+        - name: Set up Python ${{ matrix.python-version }}
+          uses: actions/setup-python@v2
+          with:
+            python-version: 3.8
 
-      - name: Pylint
-        run: |
-          python3 -m pip install --user pylint
-          # Make sure pylint doesn't regress
-          pylint python/taichi/ --disable=all --enable=$(python scripts/generate_pylint_tags.py)
-          if [ $? -eq 0 ]
-          then
-            echo "PASSED: pylint is happy"
-            exit 0
-          else
-            echo "FAILED: please run the pylint command above and make sure it passes"
-            exit 1
-          fi
+        - name: Pylint
+          run: |
+            python3 -m pip install --user pylint
+            # Make sure pylint doesn't regress
+            pylint python/taichi/ --disable=all --enable=$(python scripts/generate_pylint_tags.py)
+            if [ $? -eq 0 ]
+            then
+              echo "PASSED: pylint is happy"
+              exit 0
+            else
+              echo "FAILED: please run the pylint command above and make sure it passes"
+              exit 1
+            fi
 
-      - name: clang-tidy
-        run: |
-          # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
-          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-          docker pull ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0
-          docker run -id --user dev --name check_clang_tidy ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0 /bin/bash
-          tar -cf - ../${{ github.event.repository.name }} --mode u=+rwx,g=+rwx,o=+rwx --owner dev --group dev | docker cp - check_clang_tidy:/home/dev/
-          docker exec --user root check_clang_tidy apt install -y clang-tidy-10
-          docker exec --user dev check_clang_tidy /home/dev/taichi/.github/workflows/scripts/check_clang_tidy.sh "$CI_SETUP_CMAKE_ARGS"
-        env:
-          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
-          CI_SETUP_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=ON -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=OFF
+        - name: clang-tidy
+          run: |
+            # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
+            echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            docker pull ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0
+            docker run -id --user dev --name check_clang_tidy ghcr.io/taichi-dev/taichidev-cpu-ubuntu18.04:v0.1.0 /bin/bash
+            tar -cf - ../${{ github.event.repository.name }} --mode u=+rwx,g=+rwx,o=+rwx --owner dev --group dev | docker cp - check_clang_tidy:/home/dev/
+            docker exec --user root check_clang_tidy apt install -y clang-tidy-10
+            docker exec --user dev check_clang_tidy /home/dev/taichi/.github/workflows/scripts/check_clang_tidy.sh "$CI_SETUP_CMAKE_ARGS"
+          env:
+            CR_PAT: ${{ secrets.GITHUB_TOKEN }}
+            CI_SETUP_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=ON -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=OFF
 
   build_and_test_cpu_linux:
     name: Build and Test linux (CPU)
@@ -181,7 +181,6 @@ jobs:
           docker cp .github/workflows/scripts/unix_docker_test.sh taichi_test:/home/dev/unix_docker_test.sh
           docker cp wheel/*.whl taichi_test:/home/dev/
           docker cp ./requirements_test.txt taichi_test:/home/dev/requirements_test.txt
-          docker cp tests/ taichi_test:/home/dev/
           docker start -a taichi_test
         env:
           PY: ${{ matrix.python }}
@@ -219,13 +218,9 @@ jobs:
 
       - name: Build & Install
         run: |
-          if [[ ${{needs.check_files.outputs.run_job}} == false ]]; then
-            exit 0
-          fi
-          export PATH=`pwd`/taichi-llvm/bin/:$PATH
           .github/workflows/scripts/unix_build.sh
         env:
-          TAICHI_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=${{ matrix.with_cc }} -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
+          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=${{ matrix.with_cc }} -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
           CXX: clang++
       # [DEBUG] Copy this step around to enable debugging inside Github Action instances.
       #- name: Setup tmate session
@@ -254,7 +249,7 @@ jobs:
       - name: Build & Install
         run: |
           mkdir -m777 wheel
-          docker create -v `pwd`/wheel:/wheel --user dev --name taichi_build --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix registry.taichigraphics.com/taichidev-ubuntu18.04:v0.1.1 /home/dev/test_actions/.github/workflows/scripts/unix_docker_build.sh $PY $GPU_BUILD $PROJECT_NAME "$CI_SETUP_CMAKE_ARGS"
+          docker create -v `pwd`/wheel:/wheel --user dev --name taichi_build --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix registry.taichigraphics.com/taichidev-ubuntu18.04:v0.1.1 /home/dev/taichi/.github/workflows/scripts/unix_docker_build.sh $PY $GPU_BUILD $PROJECT_NAME "$CI_SETUP_CMAKE_ARGS"
           tar -cf - ../${{ github.event.repository.name }} --mode u=+rwx,g=+rwx,o=+rwx --owner dev --group dev | docker cp - taichi_build:/home/dev/
           docker start -a taichi_build
         env:
@@ -269,7 +264,6 @@ jobs:
           docker create --user dev --name taichi_test --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix registry.taichigraphics.com/taichidev-ubuntu18.04:v0.1.1 /home/dev/unix_docker_test.sh $PY $GPU_TEST $TI_WANTED_ARCHS
           docker cp .github/workflows/scripts/unix_docker_test.sh taichi_test:/home/dev/unix_docker_test.sh
           docker cp wheel/*.whl taichi_test:/home/dev/
-          docker cp tests/ taichi_test:/home/dev/
           docker start -a taichi_test
         env:
           PY: py38
@@ -311,11 +305,11 @@ jobs:
           $env:PATH = ";C:\taichi_llvm\bin;C:\taichi_clang\bin;" + $env:PATH
           . venv\Scripts\activate.ps1
           python -c "import taichi"
-          ti example laplace
+          python examples/algorithm/laplace.py
           ti diagnose
           ti changelog
           echo wanted arch: $env:TI_WANTED_ARCHS
-          python tests/run_tests.py -vr2 -t2 -a "$env:TI_WANTED_ARCHS"
+          ti test -vr2 -t2 -a "$env:TI_WANTED_ARCHS"
         env:
           PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
           TI_WANTED_ARCHS: "cpu"
@@ -345,17 +339,27 @@ jobs:
           rm -rf $HOME/Library/Python/3.8/lib/python/site-packages/taichi
           .github/workflows/scripts/unix_build.sh
         env:
-          TAICHI_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CUDA:BOOL=OFF -DTI_WITH_CC:BOOL=OFF -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=ON
+          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CUDA:BOOL=OFF -DTI_WITH_CC:BOOL=OFF -DTI_WITH_VULKAN:BOOL=OFF -DTI_BUILD_TESTS:BOOL=ON
           CXX: clang++
 
       - name: Test
         run: |
           export PATH=$PATH:$HOME/Library/Python/3.8/bin
           python3 -m pip install -r requirements_test.txt
-          ti example laplace
+          python3 examples/algorithm/laplace.py
           TI_LIB_DIR=`python3 -c "import taichi;print(taichi.__path__[0])" | tail -1`
           TI_LIB_DIR="$TI_LIB_DIR/lib" ./build/taichi_cpp_tests
           echo wanted archs: $TI_WANTED_ARCHS
-          python3 tests/run_tests.py -vr2 -t4 -x
+          ti test -vr2 -t4 -x
         env:
           TI_WANTED_ARCHS: "metal,cpu"
+
+  get_results:
+    name: Get and Check the Results 
+    needs: [check_files, check_code_format, check_static_analyzer, build_and_test_cpu_linux, build_and_test_windows, build_and_test_gpu_linux, build_and_test_m1, build_and_test_cpu_mac]
+    runs_on: ubuntu-latest
+    steps:
+      env:
+        $RESULTS: {{ needs }}
+      run:
+        echo $RESULTS
