revert

diff --git a/.github/workflows/presubmit.yml b/.github/workflows/presubmit.yml
--- a/.github/workflows/presubmit.yml
+++ b/.github/workflows/presubmit.yml
@@ -4,22 +4,74 @@ on:
     types: [opened, synchronize, reopened]
 
 jobs:
-  docker_cpu_build:
+  title_format:
+    name: Check PR Title
+    if: ${{ github.event.pull_request }}
     runs-on: ubuntu-latest
-    container: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
     steps:
-      - run: |
-        ti test
+      - uses: actions/checkout@v2
+      - uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
 
-  docker_gpu_build:
-    runs-on: [self-hosted, cuda, vulkan]
-    container: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
+      - name: Run PR Title Checker
+        run: |
+          pip install semver GitPython
+          python misc/ci_check_pr_title.py "$PR_TITLE"
+        env:
+          PR_TITLE: ${{ github.event.pull_request.title }}
+
+  check_code_format:
+    name: Check Code Format
+    runs-on: ubuntu-latest
+    # This job will be required to pass before merging to master branch.
     steps:
-      - run: |
-        ti test
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+
+      - name: Setup git & clang-format
+        run: |
+          git config user.email "taichigardener@gmail.com"
+          git config user.name "Taichi Gardener"
+          git checkout -b _fake_squash
+          git remote add upstream https://github.com/taichi-dev/taichi.git
+          git fetch upstream master
+          sudo apt install clang-format-10
+      - name: Cache PIP
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements_dev.txt') }}
+
+      - name: Install requirements
+        run: |
+          python3 -m pip install --user -r requirements_dev.txt
+      - name: Check code format
+        run: |
+          python3 misc/code_format.py
+          git checkout -b _enforced_format
+          git commit -am "enforce code format" || true
+          # exit with 1 if there were differences:
+          git diff _fake_squash _enforced_format --exit-code
+      - name: Pylint
+        run: |
+          # Make sure pylint doesn't regress
+          pylint python/taichi/ --disable=all --enable=C0121,C0415
+          if [ $? -eq 0 ]
+          then
+            echo "PASSED: pylint is happy"
+            exit 0
+          else
+            echo "FAILED: please run the pylint command above and make sure it passes"
+            exit 1
+          fi
 
   performance_monitoring:
     name: Performance monitoring (NVGPU)
+    needs: check_code_format
     timeout-minutes: 60
     runs-on: [self-hosted, x64, cuda, linux, benchmark]
     steps:
