ci fix

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,7 +28,6 @@ jobs:
           [ -z "${{ github.event.action }}" ] && matrix_osx="[{\"name\":\"taichi-nightly\",\"python\":\"3.8\"}]"
           [ -z "${{ github.event.action }}" ] || matrix_osx="[{\"name\":\"taichi\",\"python\":\"3.8\"},{\"name\":\"taichi\",\"python\":\"3.9\"}]"
           echo ::set-output name=matrix_osx::{\"include\":$(echo $matrix_osx)}\"
-
   build_and_upload_linux:
     name: Build and Upload (linux only)
     needs: matrix_prep
@@ -47,15 +46,25 @@ jobs:
           # automatically. So we don't activate and use desired python version
           # directly.
           export PATH=/home/buildbot/miniconda3/envs/$PYTHON/bin:$PATH
-          export PATH=/usr/local/cuda/bin:$PATH
-          .github/workflows/scripts/unix_build.sh
+          TAICHI_REPO_DIR=`pwd`
+          export PATH=$LLVM_LIB_ROOT_DIR/bin:/usr/local/cuda/bin:$PATH
+          export LLVM_DIR=$LLVM_LIB_ROOT_DIR/lib/cmake/llvm
+          export CXX=clang++-8
+          python3 -m pip uninstall taichi taichi-nightly -y
+          python3 -m pip install -r requirements_dev.txt
+          python3 -m pip install twine
+          cd python
+          git fetch origin master
+          export TAICHI_CMAKE_ARGS=$CI_SETUP_CMAKE_ARGS
+          python3 build.py build --project_name $PROJECT_NAME
+          cd ..
+          NUM_WHL=`ls dist/*.whl | wc -l`
+          if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1; fi
+          python3 -m pip install dist/*.whl
         env:
           LLVM_LIB_ROOT_DIR: /opt/taichi-llvm-10.0.0
-          LLVM_PATH: /opt/taichi-llvm-10.0.0/bin
-          LLVM_DIR: /opt/taichi-llvm-10.0.0/lib/cmake/llvm
           BUILD_NUM_THREADS: 8
           CI_SETUP_CMAKE_ARGS: -DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_OPENGL:BOOL=ON -DTI_WITH_CC:BOOL=OFF -DTI_BUILD_TESTS:BOOL=${{ matrix.with_cpp_tests }}
-          CXX: clang++-8
           PROJECT_NAME: ${{ matrix.name }}
           PYTHON: ${{ matrix.python }}
 
@@ -68,11 +77,18 @@ jobs:
       - name: Test
         run: |
           export PATH=/home/buildbot/miniconda3/envs/$PYTHON/bin:$PATH
-          .github/workflows/scripts/unix_test.sh
+          python3 examples/algorithm/laplace.py
+          export DISPLAY=:1
+          hash -r
+          glewinfo
+          ti diagnose
+          ti changelog
+          ti test -vr2 -t2 -k "not ndarray and not torch"
+          # ndarray test might OOM if run with -t2.
+          # FIXME: unify this with presubmit.yml to avoid further divergence
+          ti test -vr2 -t1 -k "ndarray or torch"
         env:
           PYTHON: ${{ matrix.python }}
-          DISPLAY: :1
-          GPU_TEST: ON
 
       - name: Upload PyPI
         env:
@@ -83,11 +99,9 @@ jobs:
           PYTHON: ${{ matrix.python }}
         run: |
           export PATH=/home/buildbot/miniconda3/envs/$PYTHON/bin:$PATH
-          python3 -m pip install twine
           cd python
           if [ $PROJECT_NAME == "taichi-nightly" ]; then export PYPI_PWD="$NIGHT_PWD" && python3 build.py upload --skip_build --testpypi --project_name $PROJECT_NAME
           elif [ $PROJECT_NAME == "taichi" ]; then export PYPI_PWD="$PROD_PWD" && python3 build.py upload --skip_build; fi
-
   build_and_upload_mac:
     name: Build and Upload (macOS only)
     needs: matrix_prep
@@ -142,7 +156,6 @@ jobs:
           python examples/algorithm/laplace.py
           ti diagnose
           ti test -vr2 -t2
-
       - name: Upload PyPI
         env:
           # https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
@@ -153,7 +166,6 @@ jobs:
           cd python
           if [ $PROJECT_NAME == "taichi-nightly" ]; then export PYPI_PWD="$NIGHT_PWD" && python build.py upload --skip_build --testpypi --project_name $PROJECT_NAME
           elif [ $PROJECT_NAME == "taichi" ]; then export PYPI_PWD="$PROD_PWD" && python build.py upload --skip_build; fi
-
   build_and_upload_m1:
     name: Build and Upload (Apple M1)
     needs: matrix_prep
@@ -210,7 +222,6 @@ jobs:
           cd python
           if [ $PROJECT_NAME == "taichi-nightly" ]; then export PYPI_PWD="$NIGHT_PWD" && python3 build.py upload --skip_build --testpypi --project_name $PROJECT_NAME
           elif [ $PROJECT_NAME == "taichi" ]; then export PYPI_PWD="$PROD_PWD" && python3 build.py upload --skip_build; fi
-
   build_and_upload_macos_1014:
     name: Build and Upload (macos 1014)
     needs: matrix_prep
@@ -275,8 +286,6 @@ jobs:
           cd python
           if [ $PROJECT_NAME == "taichi-nightly" ]; then export PYPI_PWD="$NIGHT_PWD" && python3 build.py upload --skip_build --testpypi --project_name $PROJECT_NAME
           elif [ $PROJECT_NAME == "taichi" ]; then export PYPI_PWD="$PROD_PWD" && python3 build.py upload --skip_build; fi
-
-
   build_and_upload_windows:
     name: Build and Upload (Windows only)
     needs: matrix_prep
@@ -306,7 +315,6 @@ jobs:
           Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/VulkanSDK-1.2.189.0-Installer.exe" -OutFile VulkanSDK.exe
           $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
           $installer.WaitForExit();
-
       - name: Build Python Wheel
         shell: powershell
         run: |
@@ -347,7 +355,6 @@ jobs:
           python examples/algorithm/laplace.py
           python bin/taichi diagnose
           python bin/taichi test -vr2 -t2
-
       - name: Upload PyPI
         shell: powershell
         env:
