test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -53,16 +53,18 @@ jobs:
           python -m pip install --user numpy pybind11 gitpython
           python setup.py develop
 
-          #- name: Install Wheel and Test
-          #  run: |
-          #    TAICHI_REPO_DIR=`pwd`
-          #    export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
-          #    NUM_WHL=`ls dist/*.whl | wc -l`
-          #    if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1 ; fi
-          #    pip install dist/*.whl
-          #    python examples/algorithm/laplace.py
-          #    ti diagnose
-          #    ti test -vr2 -t2
+      - name: Test
+        run: |
+        #    TAICHI_REPO_DIR=`pwd`
+        #    export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
+        #    NUM_WHL=`ls dist/*.whl | wc -l`
+        #    if [ $NUM_WHL -ne 1 ]; then echo 'ERROR: created more than 1 whl.' && exit 1 ; fi
+        #    pip install dist/*.whl
+          python examples/algorithm/laplace.py
+          ti diagnose
+          ti test -t2
+          echo "${{ github.event.action }}"
+
           #    
           #- name: Archive Wheel Artifacts
           #  # https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts
@@ -141,7 +143,8 @@ jobs:
           python -c "import taichi"
           python examples/algorithm/laplace.py
           python bin/taichi diagnose
-          python bin/taichi test -Cvr2 -t2
+          python bin/taichi test -t2
+          echo "${{ github.event.action }}"
 
       - name: Upload PyPI
         env:
